# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma_original', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=1000)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=140)),
                ('calificacion', models.IntegerField()),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubTitlesApp.Obra')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubTitlesApp.Obra')),
            ],
        ),
        migrations.CreateModel(
            name='Teatro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('contrasenia', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubTitlesApp.Obra')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubTitlesApp.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubTitlesApp.Usuario'),
        ),
        migrations.AddField(
            model_name='obra',
            name='teatro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SubTitlesApp.Teatro'),
        ),
    ]
