# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SubTitlesApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('airline', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='obra',
            name='teatro',
        ),
        migrations.RemoveField(
            model_name='review',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='review',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='subtitles',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='obra',
        ),
        migrations.RemoveField(
            model_name='visita',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Obra',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Subtitles',
        ),
        migrations.DeleteModel(
            name='Teatro',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
